name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-pc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: yarn
      
      - name: Build the web assets
        run: yarn build

      - name: Build electron and Publish
        run: yarn electron:build --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: yarn
        
      - name: Build the web assets
        run: yarn build
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: android-30
          ndk: 21.4.7075529
          build-tools: 30.0.3

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > my-release-key.keystore

      - name: Build Android APK
        run: yarn android:build
      
      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore my-release-key.keystore \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          android/app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}
      
      - name: Verify APK Signature
        run: jarsigner -verify -verbose -certs android/app/build/outputs/apk/release/app-release-unsigned.apk
        
      - name: Align APK (optional but recommended)
        run: |
          ZIPALIGN=$(find $ANDROID_HOME/build-tools/ -name zipalign | sort | tail -n 1) 
          $ZIPALIGN -v 4 android/app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      
      - name: Authenticate with GitHub for APK Publishing
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
      
      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Publish APK to Another Repository
        run: |
          if gh release view ${{ env.TAG_NAME }} -R jianzhichun/useflow-release >/dev/null 2>&1; then
            echo "Release ${{ env.TAG_NAME }} already exists. Uploading APK..."
            gh release upload ${{ env.TAG_NAME }} app-release.apk -R jianzhichun/useflow-release
          else
            echo "Creating new release ${{ env.TAG_NAME }} and uploading APK..."
            gh release create ${{ env.TAG_NAME }} app-release.apk -R jianzhichun/useflow-release --title "Release ${{ env.TAG_NAME }}" --notes "APK release"
          fi
