name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Electron app
        run: yarn package

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            electron/*.exe
            electron/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
